const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'IKU V100 double Sim',
      slug: 'IKU V100 double Sim',
      category: 'Portable',
      image: '/images/p5.jfif', //679x829px
      price: 200,
      countInStock: 5,
      brand: 'Sumsung',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p4.jpg', //679x829px
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nokia touches 40T 2Sim',
      slug: 'Nokia touches 40T 2Sim',
      category: 'Portable',
      image: '/images/p6.jfif', //679x829px
      price: 40,
      countInStock: 5,
      brand: 'Nokia',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Xiaomi Redmi 10 4GO 128GO',
      slug: 'Xiaomi Redmi 10 4GO 128GO',
      category: 'Portable',
      image: '/images/p7.jfif', //679x829px
      price: 400,
      countInStock: 5,
      brand: 'Redmi',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'OPPO A94 5G 8GO 128GO',
      slug: 'OPPO A94 5G 8GO 128GO',
      category: 'Portable',
      image: '/images/p8.jfif', //679x829px
      price: 55,
      countInStock: 5,
      brand: 'OPPO',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
